# travis-ci
os: linux
dist: bionic
sudo: required

language: nodejs
    - '10'
    - '12'

services:
    - docker 

install:
    - npm install

script:
    - chmod +x scripts/build.sh && ./scripts/build.sh
