# travis-ci
os: linux
dist: bionic
sudo: required

language: nodejs
    - '10'
    - '12'

services:
    - docker 

install:
    - npm install

script:
    - chmod +x clean_gh_artfect.sh && sh clean_gh_artfect.sh
